###
PUT http://localhost:3000/api/user
content-type: application/json

{
   "userName": "shravan",
   "firstName": "shravan",
   "lastName": "santhanam",
   "role": "manager",
   "dob": "2025-07-26T21:20:51.952Z",
   "email": "shravan@in.com",
   "location": "usa"
}


###
GET http://localhost:3000/api/user


###
POST http://localhost:3000/api/user
content-type: application/json

{
    "_id": "68854b749784ec281f80feb0",
    "userName": "s shrvan",
    "dob":"2013-10-26T21:41:08.567Z"
}

###
DELETE http://localhost:3000/api/user
content-type: application/json

{
    "_id": "688550919784ec281f80feb2"
}